fix: ignore not throw on invalid response headers
github/fetch pull request #950
Opened 2021-04-14 00:08 UTC by pke

@JakeChampion I think the fix is fine, however I struggle with the test. It runs into the same problem that the response headers are validated. But I can't figure out which package supplies this code. None of the `node_modules` has a `_http_outgoing.js` that I could monkey-patch for this one response to not validate the response headers.

I also can't just test `parseHeaders()` since its private and not globally exported (rightfully so).

So do you have any idea how to test my fix properly?

Fixes #930

2021-04-14 10:45 UTC, JakeChampion commented
`_http_outgoing.js` is part of the [built-in NodeJS http module](https://github.com/nodejs/node/blob/master/lib/_http_outgoing.js), it is not possible to set a response header name in an invalid format with the built-in NodeJS http module.

The only way I can think to test this, would be to use another language to create a http server which can set a response header name in an invalid format. From the issue, we know that golang is able to do that.

I'm also happy to accept this pull-request without a test

2021-05-01 06:29 UTC, lastthyme approved these changes

2021-05-01 08:26 UTC, pke commented
I’m working on mocking xhr to Test this.

2021-05-23 09:45 UTC, ivan0117 approved these changes

2021-05-24 08:15 UTC, jmayes41 approved these changes

2021-05-26 21:19 UTC, lastthyme approved these changes

2021-06-08 18:58 UTC, devkadirselcuk approved these changes

2021-06-22 01:40 UTC, ivan0117 commented
GI

2021-06-22 01:41 UTC, ivan0117 approved these changes
n

2021-06-22 01:51 UTC, ivan0117 commented
第 53 行 8f48ca6

2021-06-22 01:52 UTC, ivan0117 approved these changes

2021-06-22 02:02 UTC, ivan0117 approved these changes
fetch.js

2021-06-22 02:03 UTC, ivan0117 reviewed
fetch.js

2021-06-22 02:03 UTC, ivan0117 approved these changes
test/test.js

2021-06-22 02:04 UTC, ivan0117 requested changes
n

2021-06-23 11:39 UTC, pke commented
What is going on here?
I am working on adding a test with mocked xhr and then put it in "Ready for review". So for the time being no more approvals needed.
And please github clean up the spam here, thanks ;)

2021-06-26 03:03 UTC, S69y approved these changes

2021-06-26 03:05 UTC, S69y commented
[61754982+sayyaf69@users.noreply.github.com](https://g.co/kgs/cza6sd) @S69y #950 
Duplicate of #

2021-06-27 04:54 UTC, 776699y approved these changes

2021-06-28 12:45 UTC, KVROHITH098 requested changes
ok it seems good but I thin there should be changes in the script

2021-07-12 14:02 UTC, mike22664 approved these changes

2021-07-12 17:48 UTC, jmayes41 approved these changes

2021-07-12 17:48 UTC, jmayes41 approved these changes

2021-07-12 17:48 UTC, jmayes41 approved these changes

2021-07-23 02:53 UTC, ivan0117 approved these changes
P

2021-07-23 02:57 UTC, ivan0117 reviewed
pke:bugfix/issue-930-normalizeName-should-not-throw

2021-07-23 03:00 UTC, ivan0117 commented
pke:bugfix/issue-930-normalizeName-should-not-throw

2021-07-23 03:00 UTC, ivan0117 requested changes
P

2021-07-23 03:01 UTC, ivan0117 approved these changes
P

2021-07-23 03:01 UTC, ivan0117 approved these changes
P

2021-07-23 08:14 UTC, KVROHITH098 commented on fetch.js
> -        headers.append(key, value)
here pls review and change this error thank you

2021-08-04 19:14 UTC, Ngcaciso approved these changes

2021-08-05 08:45 UTC, taquila123 approved these changes

2021-08-06 08:50 UTC, jmayes41 approved these changes

2021-08-14 18:21 UTC, Elpasto28 approved these changes

2021-08-18 07:44 UTC, Shah8018 approved these changes
Gd luck and tyvm

2021-09-01 22:55 UTC, SaintPatricksCoin approved these changes
test/test.js
test/server.js
fetch.js
gh pr checkout 6
TheStreet321:master

2021-09-13 13:24 UTC, Madow92 approved these changes

2021-09-13 13:25 UTC, Shah8018 commented
Ty patrix

On Mon, Sep 13, 2021, 21:24 Madeleine Nilsson ***@***.***>
wrote:

> ***@***.**** approved this pull request.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/github/fetch/pull/950#pullrequestreview-752744383>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AU3HJ5FNI5XCVR4EYT3PUCLUBX3RJANCNFSM424JYYYA>
> .
>

2021-10-18 00:24 UTC, gyorgyilibor commented
> @JakeChampion I think the fix is fine, however I struggle with the test. It runs into the same problem that the response headers are validated. But I can't figure out which package supplies this code. None of the `node_modules` has a `_http_outgoing.js` that I could monkey-patch for this one response to not validate the response headers.
> 
> I also can't just test `parseHeaders()` since its private and not globally exported (rightfully so).
> 
> So do you have any idea how to test my fix properly?
> 
> Fixes #930

2021-10-24 01:57 UTC, Unileverllc commented
> @JakeChampion I think the fix is fine, however I struggle with the test. It runs into the same problem that the response headers are validated. But I can't figure out which package supplies this code. None of the `node_modules` has a `_http_outgoing.js` that I could monkey-patch for this one response to not validate the response headers.
> 
> I also can't just test `parseHeaders()` since its private and not globally exported (rightfully so).
> 
> So do you have any idea how to test my fix properly?
> 
> Fixes #930

Its the skaldic wayvitbwas written asbtopic . You know there's play on social rivalry and then a fault where a pattern went omlqoup again

2022-01-12 20:21 UTC, inakiAndres approved these changes

2022-03-22 18:46 UTC, Izz-gbht commented
> @JakeChampion Saya rasa penyelesaiannya baik, namun saya bergelut dengan ujian itu. Ia menghadapi masalah yang sama bahawa pengepala respons disahkan. Tetapi saya tidak dapat mengetahui pakej mana yang membekalkan kod ini. Tiada satu pun `node_modules`yang `_http_outgoing.js`saya boleh tampal monyet untuk respons yang satu ini untuk tidak mengesahkan pengepala respons.
> 
> Saya juga tidak boleh hanya menguji `parseHeaders()`kerana ia peribadi dan tidak dieksport secara global (sebenarnya).
> 
> Jadi adakah anda mempunyai idea bagaimana untuk menguji pembaikan saya dengan betul?
> 
> Membetulkan #930

2022-03-22 18:46 UTC, Izz-gbht commented
Yang mana

2022-04-08 16:02 UTC, PandaSuits approved these changes
Reviwed changes, merge commits

2022-06-11 09:16 UTC, dangbetj approved these changes

2023-04-01 01:23 UTC, JakeChampion approved these changes

2023-04-01 01:40 UTC, merged